# Generated by Django 5.0 on 2025-10-05 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstacionMeteorologica',
            fields=[
                ('codigo_nacional', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_estacion', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(decimal_places=5, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=5, max_digits=10)),
                ('altura', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id_habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('forma_svg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id_oficina', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('georeferencia', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoZona',
            fields=[
                ('id_tipozona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='OficinaEstacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.BooleanField(default=False)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('codigo_nacional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estacionmeteorologica')),
                ('id_oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.oficina')),
            ],
        ),
        migrations.CreateModel(
            name='PosicionSolar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('momento', models.DateTimeField()),
                ('elevacion', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('azimut', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('codigo_nacional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estacionmeteorologica')),
            ],
        ),
        migrations.CreateModel(
            name='PrediccionClima',
            fields=[
                ('id_registro', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=4)),
                ('sensacion_termica', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('humedad_relativa', models.SmallIntegerField(blank=True, null=True)),
                ('cobertura_nubes', models.SmallIntegerField(blank=True, null=True)),
                ('prob_precipitacion', models.SmallIntegerField(blank=True, null=True)),
                ('precipitacion_qpf', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('viento_velocidad', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('viento_direccion_cardinal', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['fecha_hora_inicio'], name='core_predic_fecha_h_3399b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id_sensor', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('temperatura', 'Temperatura'), ('humedad', 'Humedad'), ('movimiento', 'Movimiento'), ('co2', 'CO2')], max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('id_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id_medicion', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unidad', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('id_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id_zona', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('orientacion', models.CharField(blank=True, choices=[('N', 'Norte'), ('S', 'Sur'), ('E', 'Este'), ('O', 'Oeste')], max_length=1, null=True)),
                ('superficie_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cantidad_equipos', models.IntegerField(blank=True, null=True)),
                ('id_habitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.habitacion')),
                ('id_oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.oficina')),
                ('id_tipozona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipozona')),
            ],
        ),
        migrations.CreateModel(
            name='Thermostato',
            fields=[
                ('id_thermostato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('id_sensor', models.OneToOneField(blank=True, help_text='Sensor asociado a este thermostat', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sensor')),
                ('id_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zona')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialZona',
            fields=[
                ('id_materialzona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('cantidad_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('id_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zona')),
            ],
        ),
        migrations.CreateModel(
            name='MedicionMeteorologica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('momento', models.DateTimeField()),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura_minima_12h', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura_maxima_12h', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humedad_relativa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('codigo_nacional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estacionmeteorologica')),
            ],
            options={
                'indexes': [models.Index(fields=['codigo_nacional', 'momento'], name='core_medici_codigo__4fbc53_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='oficinaestacion',
            constraint=models.UniqueConstraint(fields=('id_oficina', 'codigo_nacional'), name='unique_oficina_estacion'),
        ),
        migrations.AddIndex(
            model_name='posicionsolar',
            index=models.Index(fields=['momento'], name='core_posici_momento_19f6fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='posicionsolar',
            constraint=models.UniqueConstraint(fields=('codigo_nacional', 'momento'), name='unique_posicion_solar'),
        ),
        migrations.AddConstraint(
            model_name='materialzona',
            constraint=models.UniqueConstraint(fields=('id_zona', 'nombre'), name='unique_material_zona_nombre'),
        ),
    ]
